export enum Rol {
  ADMIN_SISTEMA = 'ADMIN_SISTEMA',
  DIRECTOR = 'DIRECTOR',
  COORDINADOR = 'COORDINADOR',
  SECRETARIA = 'SECRETARIA',
  REGENTE = 'REGENTE',
  CONTADOR = 'CONTADOR',
  DOCENTE = 'DOCENTE',
  ESTUDIANTE = 'ESTUDIANTE',
  PADRE_TUTOR = 'PADRE_TUTOR',
}

export enum Nivel {
  INICIAL = 'INICIAL',
  PRIMARIA = 'PRIMARIA',
  SECUNDARIA = 'SECUNDARIA',
}

export enum Instrumento {
  OBSERVACION = 'OBSERVACION',
  CUADERNO = 'CUADERNO',
  EVALUACION_ESCRITA = 'EVALUACION_ESCRITA',
  EVALUACION_ORAL = 'EVALUACION_ORAL',
  DEFENSA = 'DEFENSA',
  PIZARRA = 'PIZARRA',
  OTRO = 'OTRO',
}

export enum EstadoAsistencia {
  PRESENTE = 'PRESENTE',
  AUSENTE = 'AUSENTE',
  TARDANZA = 'TARDANZA',
}

export enum VisiblePara {
  TODOS = 'TODOS',
  DOCENTES = 'DOCENTES',
  ESTUDIANTES = 'ESTUDIANTES',
  PPFF = 'PPFF',
  INTERNOS = 'INTERNOS',
}

export enum TipoGaleria {
  FOTO = 'FOTO',
  VIDEO = 'VIDEO',
}

export enum EstadoEstudiante {
  PREINSCRITO = 'PREINSCRITO',
  ACTIVO = 'ACTIVO',
  RETIRADO = 'RETIRADO',
  TRASLADADO = 'TRASLADADO',
  EGRESADO = 'EGRESADO',
}

export enum ResultadoMatricula {
  SIN_DEFINIR = 'SIN_DEFINIR',
  EN_CURSO = 'EN_CURSO',
  PROMOVIDO = 'PROMOVIDO',
  NO_PROMOVIDO = 'NO_PROMOVIDO',
}

export enum Sexo {
  M = 'M',
  F = 'F',
}
