[phases.setup]
nixPkgs = ["chromium"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "chmod -R +x node_modules/.bin/",
  "pnpm --filter @edusync/database db:generate",
  "pnpm --filter @edusync/api build"
]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node apps/api/dist/index.js"
