[phases.setup]
nixPkgs = ["chromium", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @edusync/database db:generate",
  "pnpm --filter @edusync/api build"
]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node apps/api/dist/index.js"
